### ISSUE TITLE
Support for Debian Jessie

### ISSUE THREAD

**Issue by hansfilipelo** [CYD-poolen/wpManySiteAdmin#10]
In order to support Debian Jessie, we can either add this line... 

<pre>fastcgi_param  SCRIPT_FILENAME    $document_root/$fastcgi_script_name;</pre>

... to each nginx-config file. 

We can also add this line to the file /etc/nginx/fastcgi_params. This issue is a forum for discussing which solution that seems to be the best choice amongst these two.

**Comment by hansfilipelo** [comment]
My vote goes to adding the line to each config file
========
Pros: 
* We don't change a config file from Debian, meaning we can upgrade to the next release of that config file without issues.
* We don't need to add this step to install instructions.

Cons: 
* We need to change each individual config file for sites  on our server that's already up and running.

**Comment by Rovanion** [comment]
I agree with @hansfilipelo, there's no guarantee that adding such a line to fastcgi_params is valid for every site which isn't controlled by wpManySiteAdmin but is on the same machine using fastcgi.
